using Microsoft.EntityFrameworkCore;

namespace RealEstate.API.Models
{
    public static class ModelBuilderExtenstions
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Category>().HasData(
                new Category { Id = 1, Name = "Single Family" },            
                new Category { Id = 2, Name = "Townhouse" },            
                new Category { Id = 3, Name = "Condo" },            
                new Category { Id = 4, Name = "Manufactured" },
                new Category { Id = 5, Name = "Multi Family" },
                new Category { Id = 6, Name = "Farm" },
                new Category { Id = 7, Name = "Land" }
            );

            modelBuilder.Entity<Property>().HasData(
                new Property {Id=1,CategoryId=1,AcresLot=2.5,Address="0813 Utah Court",Bath=3,Bed=7,City="Flint",Description="Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",Price=400452,Sqft=4500,State="Michigan",YearBuilt=1995,PostalCode="48550"},
                new Property {Id=2,CategoryId=1,AcresLot=2.0,Address="7577 Drewry Alley",Bath=2,Bed=5,City="Levittown",Description="Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",Price=735137,Sqft=1200,State="Pennsylvania",YearBuilt=1996,PostalCode="19058"},
                new Property {Id=3,CategoryId=1,AcresLot=1.36,Address="15448 Mosinee Alley",Bath=5,Bed=1,City="Oakland",Description="Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",Price=341936,Sqft=4100,State="California",YearBuilt=2007,PostalCode="94611"},
                new Property {Id=4,CategoryId=1,AcresLot=4.75,Address="5673 Eagle Crest Crossing",Bath=1,Bed=2,City="El Paso",Description="Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.",Price=856639,Sqft=2000,State="Texas",YearBuilt=1984,PostalCode="79994"},
                new Property {Id=5,CategoryId=1,AcresLot=2.0,Address="5 8th Hill",Bath=4,Bed=10,City="Pittsburgh",Description="Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",Price=928706,Sqft=5000,State="Pennsylvania",YearBuilt=2009,PostalCode="15279"},
                new Property {Id=6,CategoryId=1,AcresLot=5.0,Address="191 Clyde Gallagher Parkway",Bath=2,Bed=10,City="Scranton",Description="Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.",Price=458575,Sqft=3000,State="Pennsylvania",YearBuilt=1998,PostalCode="18514"},
                new Property {Id=7,CategoryId=1,AcresLot=3.0,Address="72136 Thompson Junction",Bath=1,Bed=3,City="Washington",Description="Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",Price=163887,Sqft=2000,State="District of Columbia",YearBuilt=2008,PostalCode="20397"},
                new Property {Id=8,CategoryId=1,AcresLot=1.75,Address="646 Spenser Court",Bath=5,Bed=1,City="Charleston",Description="Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.",Price=615743,Sqft=2500,State="West Virginia",YearBuilt=1993,PostalCode="25356"},
                new Property {Id=9,CategoryId=1,AcresLot=5.3,Address="658 Meadow Ridge Plaza",Bath=1,Bed=10,City="Merrifield",Description="Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.",Price=609719,Sqft=2000,State="Virginia",YearBuilt=1987,PostalCode="22119"},
                new Property {Id=10,CategoryId=1,AcresLot=5.1,Address="45 Bartelt Place",Bath=2,Bed=6,City="Cincinnati",Description="Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",Price=774601,Sqft=4000,State="Ohio",YearBuilt=1997,PostalCode="45208"},
                new Property {Id=11,CategoryId=1,AcresLot=9.0,Address="2 Saint Paul Trail",Bath=3,Bed=5,City="Evansville",Description="In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.",Price=139964,Sqft=53,State="Indiana",YearBuilt=1986,PostalCode="47725"},
                new Property {Id=12,CategoryId=1,AcresLot=3.7,Address="9782 Center Trail",Bath=1,Bed=4,City="New York City",Description="Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.",Price=254629,Sqft=3500,State="New York",YearBuilt=2011,PostalCode="10184"},
                new Property {Id=13,CategoryId=2,AcresLot=0.10,Address="1 Talmadge Avenue",Bath=4,Bed=8,City="San Antonio",Description="Aenean sit amet justo.",Price=209806,Sqft=37,State="Texas",YearBuilt=1999,PostalCode="78220"},
                new Property {Id=14,CategoryId=2,AcresLot=0.10,Address="1493 Mosinee Lane",Bath=2,Bed=3,City="Lakeland",Description="Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.",Price=140010,Sqft=1700,State="Florida",YearBuilt=1998,PostalCode="33805"},
                new Property {Id=15,CategoryId=2,AcresLot=0.10,Address="68932 Lyons Circle",Bath=2,Bed=7,City="Washington",Description="In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",Price=642327,Sqft=3000,State="District of Columbia",YearBuilt=2002,PostalCode="20205"},
                new Property {Id=16,CategoryId=2,AcresLot=0.10,Address="0335 Lindbergh Place",Bath=2,Bed=4,City="Santa Ana",Description="Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",Price=596003,Sqft=2100,State="California",YearBuilt=2002,PostalCode="92705"},
                new Property {Id=17,CategoryId=2,AcresLot=0.10,Address="576 Glendale Circle",Bath=1,Bed=10,City="Reading",Description="Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.",Price=474589,Sqft=4000,State="Pennsylvania",YearBuilt=2002,PostalCode="19610"},
                new Property {Id=18,CategoryId=2,AcresLot=0.10,Address="857 5th Way",Bath=3,Bed=7,City="Sacramento",Description="Etiam pretium iaculis justo.",Price=603300,Sqft=87,State="California",YearBuilt=1980,PostalCode="94286"},
                new Property {Id=19,CategoryId=2,AcresLot=0.10,Address="4387 Acker Circle",Bath=5,Bed=5,City="Memphis",Description="Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",Price=764247,Sqft=97,State="Tennessee",YearBuilt=2008,PostalCode="38119"},
                new Property {Id=20,CategoryId=2,AcresLot=0.10,Address="0 Forest Dale Avenue",Bath=3,Bed=9,City="Los Angeles",Description="In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.",Price=761101,Sqft=83,State="California",YearBuilt=2006,PostalCode="90025"},
                new Property {Id=21,CategoryId=2,AcresLot=0.10,Address="2117 Sutteridge Center",Bath=3,Bed=7,City="Lawrenceville",Description="Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",Price=295002,Sqft=2100,State="Georgia",YearBuilt=1992,PostalCode="30045"},
                new Property {Id=22,CategoryId=2,AcresLot=0.10,Address="607 Quincy Parkway",Bath=2,Bed=5,City="New Brunswick",Description="Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.",Price=334096,Sqft=1000,State="New Jersey",YearBuilt=1991,PostalCode="08922"},
                new Property {Id=23,CategoryId=2,AcresLot=0.10,Address="6084 Shopko Avenue",Bath=4,Bed=4,City="Philadelphia",Description="Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",Price=593823,Sqft=3000,State="Pennsylvania",YearBuilt=1995,PostalCode="19151"},
                new Property {Id=24,CategoryId=2,AcresLot=0.10,Address="99 Golf Road",Bath=2,Bed=10,City="Rockville",Description="Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.",Price=490336,Sqft=86,State="Maryland",YearBuilt=1999,PostalCode="20851"},
                new Property {Id=25,CategoryId=3,AcresLot=0,Address="1 Thierer Road",Bath=5,Bed=1,City="Houston",Description="In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.",Price=515572,Sqft=1900,State="Texas",YearBuilt=2004,PostalCode="77266"},
                new Property {Id=26,CategoryId=3,AcresLot=0,Address="68823 Sachs Road",Bath=4,Bed=2,City="Tucson",Description="Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.",Price=578860,Sqft=1800,State="Arizona",YearBuilt=1998,PostalCode="85732"},
                new Property {Id=27,CategoryId=3,AcresLot=0,Address="73 Parkside Way",Bath=5,Bed=10,City="Huntington",Description="Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.",Price=347153,Sqft=28,State="West Virginia",YearBuilt=2010,PostalCode="25705"},
                new Property {Id=28,CategoryId=3,AcresLot=0,Address="1082 Gateway Street",Bath=2,Bed=4,City="Boston",Description="Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.",Price=529718,Sqft=2400,State="Massachusetts",YearBuilt=2001,PostalCode="02104"},
                new Property {Id=29,CategoryId=3,AcresLot=0,Address="19175 Dorton Hill",Bath=3,Bed=9,City="Mobile",Description="Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.",Price=510397,Sqft=3000,State="Alabama",YearBuilt=2011,PostalCode="36616"},
                new Property {Id=30,CategoryId=3,AcresLot=0,Address="29277 School Place",Bath=4,Bed=8,City="Pittsburgh",Description="Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",Price=190339,Sqft=1000,State="Pennsylvania",YearBuilt=2007,PostalCode="15255"},
                new Property {Id=31,CategoryId=3,AcresLot=0,Address="7266 Elka Junction",Bath=2,Bed=10,City="Toledo",Description="Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.",Price=355668,Sqft=2900,State="Ohio",YearBuilt=1994,PostalCode="43605"},
                new Property {Id=32,CategoryId=3,AcresLot=0,Address="32034 Pennsylvania Street",Bath=4,Bed=2,City="Carlsbad",Description="Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.",Price=636436,Sqft=2600,State="California",YearBuilt=2012,PostalCode="92013"},
                new Property {Id=33,CategoryId=4,AcresLot=5.0,Address="3 Mayfield Lane",Bath=4,Bed=3,City="Los Angeles",Description="In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.",Price=861656,Sqft=3400,State="California",YearBuilt=2004,PostalCode="90015"},
                new Property {Id=34,CategoryId=4,AcresLot=8.0,Address="21 Pleasure Place",Bath=3,Bed=10,City="Tacoma",Description="Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.",Price=627695,Sqft=5000,State="Washington",YearBuilt=2005,PostalCode="98464"},
                new Property {Id=35,CategoryId=4,AcresLot=6.5,Address="6512 Banding Alley",Bath=4,Bed=5,City="Glendale",Description="Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.",Price=271109,Sqft=2200,State="Arizona",YearBuilt=1994,PostalCode="85311"},
                new Property {Id=36,CategoryId=4,AcresLot=2.75,Address="478 Prentice Junction",Bath=1,Bed=5,City="Winston Salem",Description="Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",Price=412540,Sqft=3200,State="North Carolina",YearBuilt=2004,PostalCode="27110"},
                new Property {Id=37,CategoryId=4,AcresLot=3.0,Address="718 Talmadge Hill",Bath=5,Bed=2,City="Dallas",Description="Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",Price=617786,Sqft=22,State="Texas",YearBuilt=1999,PostalCode="75216"},
                new Property {Id=38,CategoryId=4,AcresLot=4.5,Address="59006 Maple Wood Street",Bath=2,Bed=8,City="Jackson",Description="Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",Price=373899,Sqft=3100,State="Mississippi",YearBuilt=1993,PostalCode="39282"},
                new Property {Id=39,CategoryId=4,AcresLot=3.3,Address="5 Karstens Alley",Bath=3,Bed=2,City="Charlottesville",Description="Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.",Price=394231,Sqft=2700,State="Virginia",YearBuilt=2011,PostalCode="22908"},
                new Property {Id=40,CategoryId=4,AcresLot=3.0,Address="26427 Petterle Trail",Bath=1,Bed=3,City="Jackson",Description="Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",Price=663338,Sqft=1800,State="Mississippi",YearBuilt=1996,PostalCode="39282"},
                new Property {Id=41,CategoryId=5,AcresLot=9.8,Address="6 Continental Court",Bath=5,Bed=6,City="Washington",Description="Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.",Price=522880,Sqft=2300,State="District of Columbia",YearBuilt=1992,PostalCode="20436"},
                new Property {Id=42,CategoryId=5,AcresLot=6.3,Address="6 Swallow Center",Bath=2,Bed=3,City="West Palm Beach",Description="In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",Price=685949,Sqft=2000,State="Florida",YearBuilt=2009,PostalCode="33411"},
                new Property {Id=43,CategoryId=5,AcresLot=4.6,Address="550 Briar Crest Terrace",Bath=2,Bed=9,City="Chattanooga",Description="Aliquam erat volutpat. In congue. Etiam justo.",Price=390423,Sqft=31,State="Tennessee",YearBuilt=1999,PostalCode="37450"},
                new Property {Id=44,CategoryId=5,AcresLot=8.3,Address="5469 Rowland Terrace",Bath=4,Bed=4,City="Jacksonville",Description="Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",Price=561397,Sqft=900,State="Florida",YearBuilt=2010,PostalCode="32215"},
                new Property {Id=45,CategoryId=5,AcresLot=2.25,Address="4 Kenwood Circle",Bath=2,Bed=10,City="Greensboro",Description="Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",Price=604789,Sqft=3000,State="North Carolina",YearBuilt=2011,PostalCode="27455"},
                new Property {Id=46,CategoryId=6,AcresLot=3.8,Address="45883 Toban Road",Bath=5,Bed=3,City="Littleton",Description="Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.",Price=913330,Sqft=3100,State="Colorado",YearBuilt=1997,PostalCode="80126"},
                new Property {Id=47,CategoryId=6,AcresLot=1.75,Address="41 Mallard Trail",Bath=2,Bed=8,City="Hattiesburg",Description="Etiam pretium iaculis justo. In hac habitasse platea dictumst.",Price=223266,Sqft=900,State="Mississippi",YearBuilt=1985,PostalCode="39404"},
                new Property {Id=48,CategoryId=6,AcresLot=1.0,Address="09043 Superior Terrace",Bath=5,Bed=9,City="Youngstown",Description="Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.",Price=187238,Sqft=700,State="Ohio",YearBuilt=1995,PostalCode="44511"},
                new Property {Id=49,CategoryId=6,AcresLot=1.5,Address="5 Bellgrove Trail",Bath=4,Bed=2,City="San Bernardino",Description="In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.",Price=825987,Sqft=1000,State="California",YearBuilt=1994,PostalCode="92424"},
                new Property {Id=50,CategoryId=6,AcresLot=2.5,Address="67 Aberg Street",Bath=1,Bed=2,City="Omaha",Description="Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.",Price=503678,Sqft=800,State="Nebraska",YearBuilt=2005,PostalCode="68164"}
            );
        }
    }
}